
["General Settings"]
	#The minimum distance apart in chunks that land towers can spawn. Default: 16 chunks
	"Land minimum distance" = 46

["Advanced Settings --take note of the range for each value"]

	["Advanced Settings --take note of the range for each value"." Values outside the ranges will be discarded"]
		#How much of the tower is destroyed after defeating the golem. Default: 75% of tower.
		#Range: 0.0 ~ 1.0
		"Percent of Tower to destroy" = 0.84
		#This value is added to the Land Tower minimum distance value above to get the average distance between Land Towers for spawning
		#I.E. if you leave the minimum distance at 20, and change this value to 10 then Land Towers would spawn a minimum of 20 chunks apart, and on average 30 chunks apart
		#Range: 1 ~ 100
		"Land average modifier" = 10

