
#Client Configs
[general]
	show_low_mana_warning = true
	show_durability = true
	render_floating_damage = true
	render_death_stats = true
	only_render_mob_looked_at = true
	#Allowed Values: BORDER, FULL
	ITEM_RARITY_BACKGROUND_TYPE = "BORDER"
	#Allowed Values: RPG, NONE
	PLAYER_GUI_TYPE = "RPG"
	render_mob_hp_gui = false
	render_mob_bar = false
	render_item_rarity_background = true
	#Range: 0.0 ~ 1.0
	ITEM_RARITY_OPACITY = 0.75
	#Allowed Values: BOTTOM_CENTER, TOP_LEFT
	GUI_POSITION = "TOP_LEFT"

